### ISSUE TITLE
feature support page needs update

### ISSUE THREAD

**Issue by pszi1ard** [hipSYCL/compiler-support#1]
Please update https://github.com/hipSYCL/featuresupport to reflect the most recent state of hipSYCL.

**Comment by illuhad** [comment]
Can you specify where you think it is outdated? I have updated it right before the 0.9 release, so it should be current (but it might be that I have forgotten something).

**Comment by pszi1ard** [comment]
I had the impression that I saw something with an "X" that should have been a tickmark, but I can't find it now; one additional thing that I misinterpreted was the (PR) link which I initially thought meant that the feature is supported and is WIP at the linked PR. I realize that's not the case.

**Comment by pszi1ard** [comment]
Right, I originally thought "host tasks" was a subset of the new "Enqueue custom operation" feature with the latter allowing more room for optimization, but I realize now that that's perhaps not the case. However the wording of the docs reads seems to suggest that the enqueue custom operation extension has abilities _additional_ to SYCL host tasks:
"allow enqueuing additional backend operations without having the execution flow return to the host."
Can you please clarify my confusion?

**Comment by illuhad** [comment]
>  one additional thing that I misinterpreted was the (PR) link which I initially thought meant that the feature is supported and is WIP at the linked PR. I realize that's not the case.

Yes, the PR links point to the PR *after* it was merged for reference. I have just committed a change to clarify that.

> Right, I originally thought "host tasks" was a subset of the new "Enqueue custom operation" feature with the latter allowing more room for optimization, but I realize now that that's perhaps not the case. However the wording of the docs reads seems to suggest that the enqueue custom operation extension has abilities additional to SYCL host tasks:
"allow enqueuing additional backend operations without having the execution flow return to the host."
Can you please clarify my confusion?

Ah, I see. So, the implementation of that extension is independent of host tasks and works differently than SYCL 2020 host tasks. Host tasks are indeed not yet implemented. Host tasks are not a clear subset of custom operations. There is some overlap as far as the use case for these features is concerned (as described in the documentation for the extension) but there are substantial differences what can be done with them.

As the name suggests, a SYCL 2020 host task is a generic task that executes on the host and synchronizes as part of the SYCL task graph. You *can* execute backend interop operations inside a host task, but you don't have to. You can put arbitrary host code inside of it.

A consequence of this is that you may have additional synchronization between host and device *if* you want to do backend interop. Let's assume you have some SYCL device kernels running on GPU, then want to do some cuBlas call, and then continue running SYCL kernels on GPU.

Because a host task executes as part of the SYCL task graph, it may have to wait for dependencies to complete, e.g. preceding kernels that modify the same SYCL buffers. So, with host tasks you might get something like this (time axis is downward):
```
                                Submit SYCL kernel1 (CPU)
                                Submit SYCL kernel2 (CPU)
                                Submit host task (CPU)
                                Submit SYCL kernel3 (CPU)
SYCL kernel1 (GPU) 
SYCL kernel2 (GPU) 
                                host task (CPU)
                                cuBlas submits operations (CPU)
cuBlas Kernel (GPU)
SYCL kernel3 (GPU)
```
Of course, the host task running on CPU and the fact that the cuBlas submission is stalling subsequent operations on the GPU can introduce additional latency.

The enqueue custom operation extension is not meant for executing arbitrary host code within the SYCL task graph. It's meant to *enqueue* additional operations when the task graph is submitted to device. With this extension you can get something like this:

```
                                Submit SYCL kernel1 (CPU)
                                Submit SYCL kernel2 (CPU)
                                enqueue custom operation (CPU)
                                cuBlas submits operations (CPU) 
                                Submit SYCL kernel3 (CPU)
SYCL kernel1 (GPU) 
SYCL kernel2 (GPU) 
cuBlas Kernel (GPU)
SYCL kernel3 (GPU)
```
In this scenario, all GPU kernels can run without further interaction with the host.

(SYCL works with task graphs and out-of-order queues, I have simplified the situation somewhat by assuming that each operation depends on the previous one, i.e. the task graph is a linear dependency chain and similar to an in-order queue)
